services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8090:8090
    environment:
      - PUBLIC_PB_URL=${PUBLIC_PB_URL:-http://localhost:8090}
      - PUBLIC_POSTHOG_URL=${PUBLIC_POSTHOG_URL:-https://eu.i.posthog.com}
      - PUBLIC_POSTHOG_TOKEN=${PUBLIC_POSTHOG_TOKEN:-pub}

      - PB_EMAIL=${PB_EMAIL}
      - PB_PASSWORD=${PB_PASSWORD}

      - TG_API_ID=${TG_API_ID}
      - TG_API_HASH=${TG_API_HASH}

      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL}
    env_file:
      - .env
    volumes:
      - ./pb/pb_data:/app/pb_data
      - ./pb/session.json:/app/session.json
